# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('Book_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=200)),
                ('Publication', models.CharField(max_length=200)),
                ('Author', models.CharField(max_length=200)),
            ],
        ),
    ]
