# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-13 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Python_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('UID', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('User_Name', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=20)),
                ('Role', models.CharField(max_length=20)),
                ('logged_In', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='Book_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
