# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-05 09:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Python_App', '0008_task'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
