# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-05 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Python_App', '0009_delete_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('Task_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=500)),
                ('Desc', models.CharField(max_length=10000)),
                ('Priority', models.CharField(max_length=20)),
                ('Assigned_To', models.CharField(max_length=100)),
                ('Assigned_On', models.DateField()),
                ('ETA', models.DateTimeField()),
                ('Assigned_By', models.CharField(max_length=50)),
            ],
        ),
    ]
