# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-20 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Python_App', '0010_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='Task_ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
